server.port = 8091

# DB details
spring.data.mongodb.database = journal_db
spring.data.mongodb.uri = mongodb+srv://atharva:atharva@journaldb.tafbjdj.mongodb.net/?appName=journalDB
spring.data.mongodb.auto-index-creation = true 